export const BREAKS = {
  quiet: {
    id: 'quiet',
    name: 'Quiet Pause',
    emoji: '🌿',
    accent: '#a78bfa',
    accentRgb: '167,139,250',
    trigger: "When your mind won't stop",
    durationRange: '2–5 min',
    subtitle: 'Step away. Let your thoughts settle.',
    durations: [
      { value: 120, label: '2', unit: 'min', desc: 'Quick reset' },
      { value: 180, label: '3', unit: 'min', desc: 'Short pause' },
      { value: 240, label: '4', unit: 'min', desc: 'Deeper rest' },
      { value: 300, label: '5', unit: 'min', desc: 'Full reset' },
    ],
    prompts: [
      "There's nothing you need to do right now.",
      "Let your thoughts arrive and pass.",
      "You are not your to-do list.",
      "This moment is complete.",
    ],
    phases: null,
    cycleDuration: 8000,
    recommendedFor: [0, 1, 2, 3], // indices into durations
  },
  eye: {
    id: 'eye',
    name: 'Eye Reset',
    emoji: '👁️',
    accent: '#2dd4bf',
    accentRgb: '45,212,191',
    trigger: 'When your eyes feel strained or dry',
    durationRange: '20s – 2 min',
    subtitle: 'Rest your focal muscles. Look far away.',
    durations: [
      { value: 20,  label: '20', unit: 'sec', desc: 'Quick blink' },
      { value: 60,  label: '1',  unit: 'min', desc: 'Eye break' },
      { value: 90,  label: '90', unit: 'sec', desc: 'Soft focus' },
      { value: 120, label: '2',  unit: 'min', desc: 'Full rest' },
    ],
    prompts: [
      "Find something at least 6 metres away.",
      "Let your eyes rest on the distance.",
      "Blink slowly. Let the focus soften.",
      "Close your eyes for a moment.",
    ],
    phases: ['Look away', 'Blink slowly', 'Close eyes', 'Return'],
    cycleDuration: 8000,
    recommendedFor: [0, 1, 2, 3],
  },
  breath: {
    id: 'breath',
    name: 'Breathing Reset',
    emoji: '🫁',
    accent: '#818cf8',
    accentRgb: '129,140,248',
    trigger: 'When you feel anxious or scattered',
    durationRange: '2–5 min',
    subtitle: 'Slow, deliberate. Follow the rhythm.',
    durations: [
      { value: 120, label: '2', unit: 'min', desc: 'Box breath' },
      { value: 180, label: '3', unit: 'min', desc: 'Settle in' },
      { value: 240, label: '4', unit: 'min', desc: 'Full reset' },
      { value: 300, label: '5', unit: 'min', desc: 'Deep reset' },
    ],
    prompts: [
      "Slow, quiet, deliberate.",
      "Breathe in through your nose.",
      "Hold the fullness.",
      "Release completely.",
    ],
    phases: ['Breathe in', 'Hold', 'Breathe out', 'Hold'],
    cycleDuration: 16000, // 4s×4 = 16s
    phaseDurations: [4000, 4000, 4000, 4000], // ms per phase
    recommendedFor: [0, 1, 2, 3],
  },
  stretch: {
    id: 'stretch',
    name: 'Stand & Stretch',
    emoji: '🧘',
    accent: '#fb923c',
    accentRgb: '251,146,60',
    trigger: 'When your body feels stiff or heavy',
    durationRange: '2–5 min',
    subtitle: 'Move. Your body was waiting for this.',
    durations: [
      { value: 120, label: '2', unit: 'min', desc: 'Quick move' },
      { value: 180, label: '3', unit: 'min', desc: 'Short stretch' },
      { value: 240, label: '4', unit: 'min', desc: 'Full stretch' },
      { value: 300, label: '5', unit: 'min', desc: 'Deep stretch' },
    ],
    prompts: [
      "Roll your shoulders backward — 5 slow circles.",
      "Drop your chin to your chest. Hold for 10 seconds.",
      "Reach both arms above your head. Stretch tall.",
      "Twist gently right, then left. Breathe through it.",
      "Stand on your toes. Rise and lower slowly, 8 times.",
      "Shake out your hands and wrists.",
    ],
    phases: null,
    cycleDuration: 60000,
    recommendedFor: [0, 1, 2, 3],
  },
}

export const BREAK_ORDER = ['quiet', 'eye', 'breath', 'stretch']
